name: ğŸ“…Update GTFS Static in database ğŸšˆğŸšŒ

on:
  push:
      paths:
      - './gtfs-static/current/**.zip'
      # branches:
      #   - main

jobs:
  deploy-to-current-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Checkout the repo
      - name: â›ï¸Unzip gtfs-static filesâ›ï¸
        run: |
          unzip extract-gtfs-static-zips.sh
      - uses: actions/setup-python@v2
        name: ğŸSetup Python environmentğŸ 
      - name: ğŸš©Install requirementsğŸš©
        run : pip install -r ./data-loading-service/requirements.txt
      - name: Update Database with latest datağŸ›¢
        run: python ./data-loading-service/app/gtfs_static_updater
        env:
          DB_URI: ${{secrets.API_DB_URI}}
          TARGET_DB_SCHEMA: "metro_api"